-- Nota: Tablas escritas en Oracle SQL

CREATE TABLE CUSTOMER (
    ID NUMBER PRIMARY KEY,
    USERNAME VARCHAR2(20) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR2(256) NOT NULL,
    EMAIL VARCHAR2(50) UNIQUE NOT NULL,
    PHONE VARCHAR2(15),
    FIRST_NAME VARCHAR2(50),
    LAST_NAME VARCHAR2(50),
    ADDRESS VARCHAR2(100),
    SEX VARCHAR2(2) CHECK (SEX IN ('M','F','O')),
    BIRTH_DATE DATE
);

CREATE TABLE CATEGORY (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    PATH VARCHAR2(100),
    PARENT_ID NUMBER,
    DESCRIPTION VARCHAR2(200)
);

CREATE TABLE ITEM (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50) NOT NULL,
    DESCRIPTION VARCHAR2(200),
    PRICE NUMBER(10, 2) ,
    STOCK NUMBER NOT NULL,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('AVAILABLE', 'UNAVAILABLE', 'PAUSED')),
    SELLER_ID NUMBER NOT NULL,
    FOREIGN KEY (SELLER_ID) REFERENCES CUSTOMER(ID),
    CATEGORY_ID NUMBER,
    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(ID)
);

CREATE TABLE CUSTOMER_ORDER (
    ID NUMBER PRIMARY KEY,
    ORDER_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(20) CHECK (STATUS IN ('PENDING', 'COMPLETED', 'CANCELLED')),
    QUANTITY NUMBER NOT NULL,
    TOTAL_AMOUNT NUMBER(10, 2),
    CUSTOMER_ID NUMBER NOT NULL,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
    ITEM_ID NUMBER,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);